import React, { useEffect, useState } from 'react';
import { 
  Clock, TrendingUp, ShieldAlert, CheckCircle, Activity, 
  Heart, Apple, Dumbbell, Calendar, ChevronRight, List, 
  ArrowUpRight, ArrowDownRight, X 
} from 'lucide-react';
import { 
  PieChart, Pie, Cell, ResponsiveContainer, 
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip 
} from 'recharts';

// --- 1. ANALYSIS MODAL COMPONENT ---
// This handles the "Analyze Report" button click to show a detailed pop-up
const AnalysisModal = ({ isOpen, onClose, score }) => {
  if (!isOpen) return null;
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm">
      <div className="bg-white rounded-[2.5rem] w-full max-w-lg p-8 shadow-2xl animate-in fade-in zoom-in duration-200">
        <div className="flex justify-between items-center mb-6">
          <h3 className="text-2xl font-black text-slate-900 tracking-tight">AI Clinical Analysis</h3>
          <button onClick={onClose} className="p-2 hover:bg-slate-100 rounded-full transition-colors">
            <X size={24} className="text-slate-400" />
          </button>
        </div>
        <div className="space-y-4">
          <div className="p-6 bg-blue-50 rounded-3xl border border-blue-100">
            <div className="flex items-center gap-3 mb-3 text-blue-600 font-bold uppercase text-[10px] tracking-widest">
              <Activity size={16} /> Diagnostic Summary
            </div>
            <p className="text-sm text-slate-700 leading-relaxed">
              Our ML model has analyzed your latest metrics. A risk score of <span className="font-bold text-blue-700">{score}%</span> suggests that while your cardiovascular stability is monitored, there are specific 13-factor variances—likely in blood pressure or glucose levels—that require attention.
            </p>
          </div>
          <div className="p-4 rounded-2xl bg-slate-50 border border-slate-100 text-[11px] text-slate-500 italic">
            Note: This analysis is generated by the CVD-AI system for educational purposes during your project demo.
          </div>
        </div>
        <button 
          onClick={onClose}
          className="w-full mt-8 bg-blue-600 text-white py-4 rounded-2xl font-bold hover:bg-slate-900 transition-all shadow-lg shadow-blue-100"
        >
          Close Analysis
        </button>
      </div>
    </div>
  );
};

// --- 2. RISK GAUGE COMPONENT ---
const RiskGauge = ({ score }) => {
  const data = [{ value: score }, { value: 100 - score }];
  const color = score < 30 ? '#22c55e' : score < 60 ? '#eab308' : '#ef4444';

  return (
    <div className="h-44 w-full relative flex items-center justify-center bg-white rounded-3xl border border-slate-100 shadow-sm">
      <ResponsiveContainer width="100%" height="100%">
        <PieChart>
          <Pie 
            data={data} cx="50%" cy="50%" 
            innerRadius={55} outerRadius={75} 
            paddingAngle={8} dataKey="value" stroke="none"
          >
            <Cell fill={color} cornerRadius={10} />
            <Cell fill="#f1f5f9" cornerRadius={10} />
          </Pie>
        </PieChart>
      </ResponsiveContainer>
      <div className="absolute text-center">
        <p className="text-3xl font-black text-slate-800">{score}%</p>
        <p className="text-[10px] uppercase tracking-widest text-slate-400 font-bold mt-1">Risk Index</p>
      </div>
    </div>
  );
};

// --- 3. MAIN DASHBOARD COMPONENT ---
const Dashboard = ({ token, onNewTest }) => {
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [isModalOpen, setIsModalOpen] = useState(false);

  useEffect(() => {
    fetch('http://127.0.0.1:5001/history', {
      headers: { 'Authorization': `Bearer ${token}` }
    })
    .then(res => res.json())
    .then(data => {
      setHistory(data);
      setLoading(false);
    })
    .catch(err => console.error("Error:", err));
  }, [token]);

  const chartData = [...history].reverse();
  const lastAssessment = history.length > 0 ? history[0] : null;
  const variance = history.length > 1 ? (history[0].risk_score - history[1].risk_score).toFixed(1) : 0;

  if (loading) return <div className="p-20 text-center font-bold text-slate-400 animate-pulse">Synchronizing Health Data...</div>;

  return (
    <div className="max-w-7xl mx-auto p-4 md:p-8 bg-[#f8fafc] min-h-screen space-y-8">
      
      {/* Hidden Analysis Modal */}
      <AnalysisModal 
        isOpen={isModalOpen} 
        onClose={() => setIsModalOpen(false)} 
        score={lastAssessment?.risk_score} 
      />

      {/* TOP HEADER */}
      <div className="flex justify-between items-end">
        <div className="space-y-1">
          <h2 className="text-4xl font-black text-slate-900 tracking-tight italic">Health Dashboard</h2>
          <p className="text-slate-500 font-medium flex items-center gap-2">
            <Calendar size={16} className="text-blue-500"/> Monitoring Period: Feb 2026
          </p>
        </div>
        <button 
            onClick={onNewTest} 
            className="bg-blue-600 text-white px-8 py-4 rounded-2xl font-bold hover:bg-blue-700 transition-all shadow-xl shadow-blue-200 flex items-center gap-3 active:scale-95"
        >
          New Assessment <ChevronRight size={20}/>
        </button>
      </div>

      <div className="grid grid-cols-12 gap-8">
        
        {/* LEFT COLUMN: TRENDS AND HISTORY */}
        <div className="col-span-12 lg:col-span-8 space-y-8">
          
          {/* DECORATED BLACK TREND CARD */}
          <div className="bg-slate-900 rounded-[2.5rem] p-8 text-white shadow-2xl relative overflow-hidden">
            <div className="relative z-10">
              <div className="flex justify-between items-center mb-10">
                <div>
                  <h3 className="text-xl font-bold tracking-tight">Health Progression</h3>
                  <p className="text-slate-400 text-xs">Biometric risk variance over time</p>
                </div>
                <div className={`flex items-center gap-1 px-4 py-1.5 rounded-full text-xs font-black ${variance <= 0 ? 'bg-green-500/20 text-green-400' : 'bg-red-500/20 text-red-400'}`}>
                  {variance <= 0 ? <ArrowDownRight size={14}/> : <ArrowUpRight size={14}/>}
                  {Math.abs(variance)}% CHANGE
                </div>
              </div>

              <div className="h-64 w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={chartData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                    <defs>
                      <linearGradient id="chartGradient" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.4}/>
                        <stop offset="95%" stopColor="#3b82f6" stopOpacity={0}/>
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="rgba(255,255,255,0.1)" />
                    <XAxis 
                        dataKey="timestamp" 
                        axisLine={false} 
                        tickLine={false} 
                        tick={{fill: 'rgba(255,255,255,0.3)', fontSize: 10}} 
                        minTickGap={40} 
                    />
                    <YAxis 
                        domain={[0, 100]} 
                        axisLine={false} 
                        tickLine={false} 
                        tick={{fill: 'rgba(255,255,255,0.3)', fontSize: 10}} 
                    />
                    <Tooltip 
                        contentStyle={{backgroundColor: '#0f172a', border: 'none', borderRadius: '15px', color: '#fff'}}
                        itemStyle={{color: '#3b82f6'}}
                    />
                    <Area 
                        type="monotone" 
                        dataKey="risk_score" 
                        stroke="#3b82f6" 
                        strokeWidth={4} 
                        fill="url(#chartGradient)" 
                        dot={{ r: 4, fill: '#3b82f6', strokeWidth: 2, stroke: '#0f172a' }} // The "Lines and points" decoration
                        activeDot={{ r: 6, fill: '#fff', strokeWidth: 0 }}
                    />
                  </AreaChart>
                </ResponsiveContainer>
              </div>
            </div>
            {/* Background Decoration */}
            <div className="absolute top-0 right-0 w-64 h-64 bg-blue-600/10 blur-[100px] rounded-full"></div>
          </div>

          {/* CLINICAL RECORDS TABLE (The "Before" Results) */}
          <div className="bg-white rounded-[2rem] border border-slate-100 shadow-sm overflow-hidden">
            <div className="p-6 border-b border-slate-50 flex justify-between items-center bg-slate-50/30">
              <h3 className="font-bold text-slate-800 flex items-center gap-2">
                <List size={18} className="text-blue-600"/> Clinical History
              </h3>
              <span className="text-[10px] font-black bg-blue-100 text-blue-700 px-3 py-1 rounded-full uppercase tracking-widest">
                Latest {history.length} Records
              </span>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full text-left">
                <thead>
                  <tr className="text-[11px] font-black text-slate-400 uppercase tracking-widest border-b border-slate-50">
                    <th className="px-8 py-5">Date & Time</th>
                    <th className="px-8 py-5 text-center">Risk Score</th>
                    <th className="px-8 py-5">Status</th>
                    <th className="px-8 py-5"></th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-50">
                  {history.map((item, idx) => (
                    <tr key={idx} className="group hover:bg-slate-50 transition-colors">
                      <td className="px-8 py-5">
                        <div className="flex items-center gap-3">
                          <div className="bg-slate-100 p-2 rounded-lg text-slate-400 group-hover:bg-blue-600 group-hover:text-white transition-all">
                            <Clock size={14}/>
                          </div>
                          <span className="text-sm font-bold text-slate-700 tracking-tight">{item.timestamp}</span>
                        </div>
                      </td>
                      <td className="px-8 py-5 text-center">
                        <span className={`text-base font-black ${item.risk_score > 50 ? 'text-red-600' : 'text-green-600'}`}>
                          {item.risk_score}%
                        </span>
                      </td>
                      <td className="px-8 py-5">
                        <span className={`px-4 py-1.5 rounded-full text-[10px] font-black uppercase tracking-tighter border ${
                          item.risk_score > 50 ? 'bg-red-50 text-red-600 border-red-100' : 'bg-green-50 text-green-600 border-green-100'
                        }`}>
                          {item.status}
                        </span>
                      </td>
                      <td className="px-8 py-5 text-right">
                         <ChevronRight size={18} className="text-slate-300 opacity-0 group-hover:opacity-100 transition-opacity"/>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>

        {/* RIGHT COLUMN: GAUGE & ASSISTANT */}
        <div className="col-span-12 lg:col-span-4 space-y-8">
          
          <div className="space-y-4">
            <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest ml-2">Current Risk Meter</h4>
            {lastAssessment && <RiskGauge score={lastAssessment.risk_score} />}
          </div>

          <div className="bg-white rounded-[2rem] p-8 border border-slate-100 shadow-sm">
             <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest mb-8">Priority Actions</h4>
             <div className="space-y-8">
                <div className="flex gap-5">
                  <div className="bg-orange-50 text-orange-600 p-4 h-fit rounded-2xl"><Apple size={22}/></div>
                  <div>
                    <p className="font-bold text-sm text-slate-800 leading-none">DASH Diet</p>
                    <p className="text-xs text-slate-400 mt-2 leading-relaxed">Limit sodium to &lt;2300mg/day to stabilize blood pressure.</p>
                  </div>
                </div>
                <div className="flex gap-5">
                  <div className="bg-blue-50 text-blue-600 p-4 h-fit rounded-2xl"><Dumbbell size={22}/></div>
                  <div>
                    <p className="font-bold text-sm text-slate-800 leading-none">Activity</p>
                    <p className="text-xs text-slate-400 mt-2 leading-relaxed">Include 30m of Zone-2 brisk walking daily.</p>
                  </div>
                </div>
             </div>
          </div>

          {/* CVD ASSISTANT CARD WITH FUNCTIONAL BUTTON */}
          <div className="bg-blue-600 rounded-[2.5rem] p-10 text-white shadow-xl shadow-blue-100 relative overflow-hidden group">
            <div className="relative z-10">
              <div className="bg-white/20 w-12 h-12 rounded-2xl flex items-center justify-center mb-6">
                <Activity size={24}/>
              </div>
              <h4 className="text-2xl font-black tracking-tight mb-2">CVD Assistant</h4>
              <p className="text-blue-100 text-sm leading-relaxed mb-8">
                I can analyze your physiological factors to explain why your risk is currently {lastAssessment?.risk_score}%.
              </p>
              <button 
                onClick={() => setIsModalOpen(true)}
                className="w-full bg-white text-blue-600 py-5 rounded-2xl font-black text-xs hover:bg-slate-50 transition-all shadow-lg active:scale-95 uppercase tracking-widest"
              >
                Analyze Report
              </button>
            </div>
            {/* Background Glow */}
            <div className="absolute bottom-[-20%] right-[-20%] w-40 h-40 bg-white/10 blur-3xl rounded-full group-hover:scale-150 transition-transform duration-700"></div>
          </div>
        </div>

      </div>
    </div>
  );
};

export default Dashboard;